# Generated by Django 4.2.30 on 2026-06-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('JUSTIFIED', 'Justificado')], default='PRESENT', max_length=10, verbose_name='Estado')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora registro')),
                ('confidence', models.FloatField(blank=True, null=True, verbose_name='Confianza del reconocimiento')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP origen')),
                ('registered_by', models.CharField(default='SYSTEM', max_length=20, verbose_name='Registrado por')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='schedules.schedule', verbose_name='Horario')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student', verbose_name='Estudiante')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.subject', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Registro de asistencia',
                'verbose_name_plural': 'Registros de asistencia',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(max_length=10, verbose_name='Estado anterior')),
                ('new_status', models.CharField(max_length=10, verbose_name='Nuevo estado')),
                ('reason', models.TextField(verbose_name='Motivo')),
                ('supporting_document', models.URLField(blank=True, verbose_name='Documento adjunto')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attendance_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='attendance.attendancerecord')),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modified_exceptions', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to='schedules.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_exceptions', to='students.student')),
            ],
            options={
                'verbose_name': 'Excepción de asistencia',
                'verbose_name_plural': 'Excepciones de asistencia',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='attendancerecord',
            constraint=models.UniqueConstraint(fields=('student', 'schedule'), name='unique_student_schedule', violation_error_message='El estudiante ya tiene un registro para esta sesión'),
        ),
    ]
