# Generated by Django 4.2.30 on 2026-06-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('ATTENDANCE_CONFIRM', 'Confirmación de asistencia'), ('RECOGNITION_ERROR', 'Error de reconocimiento'), ('OUT_OF_SCHEDULE', 'Fuera de horario'), ('ACCOUNT_STATUS', 'Estado de cuenta'), ('PASSWORD_CHANGED', 'Cambio de contraseña'), ('CREDENTIALS', 'Credenciales iniciales'), ('RECOVERY', 'Recuperación de contraseña')], max_length=30)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('email_sent', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
