# Generated by Django 4.2.30 on 2026-06-01 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Período')),
                ('start_date', models.DateField(verbose_name='Fecha inicio')),
                ('end_date', models.DateField(verbose_name='Fecha fin')),
                ('is_active', models.BooleanField(default=False, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Período académico',
                'verbose_name_plural': 'Períodos académicos',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_day', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes'), (6, 'Sábado')], verbose_name='Día de la semana')),
                ('start_time', models.TimeField(verbose_name='Hora inicio')),
                ('end_time', models.TimeField(verbose_name='Hora fin')),
                ('classroom', models.CharField(blank=True, max_length=50, verbose_name='Aula')),
                ('academic_period', models.CharField(max_length=20, verbose_name='Período académico')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='students.subject', verbose_name='Asignatura')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'TEACHER'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to=settings.AUTH_USER_MODEL, verbose_name='Docente')),
            ],
            options={
                'verbose_name': 'Horario',
                'verbose_name_plural': 'Horarios',
                'ordering': ['week_day', 'start_time'],
            },
        ),
    ]
