# Generated by Django 4.2.30 on 2026-06-19 04:09

from django.db import migrations

CAREERS = [
    ("Computación", "COMP"),
    ("Electricidad", "ELEC"),
    ("Automotriz", "AUTO"),
    ("Telecomunicaciones", "TELCO"),
    ("Minas", "MINAS"),
]


def seed_careers(apps, schema_editor):
    Career = apps.get_model("students", "Career")
    for name, code in CAREERS:
        Career.objects.get_or_create(code=code, defaults={"name": name})


def reverse_careers(apps, schema_editor):
    Career = apps.get_model("students", "Career")
    Career.objects.filter(code__in=[c[1] for c in CAREERS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_careers, reverse_careers),
    ]
